from SCons.Script import VariantDir, Environment, \
        Builder, Depends, Flatten
import os

VariantDir('_build', src_dir='.')

env = Environment(ENV=os.environ)
inkscape = Builder(action = 'inkscape --without-gui --export-pdf=$TARGET $SOURCE')
env['BUILDERS']['Inkscape'] = inkscape
env['BUILDERS']['Latexdiff'] = Builder(action = 'latexdiff $SOURCES > $TARGET')

svgs = [ ]

pdfs = [env.Inkscape(target="_build/" + os.path.basename(svg).replace('.svg','.pdf'), source=svg)
        for svg in svgs]

lcfit, = env.PDF(target='_build/lcfit.pdf',source='lcfit.tex')
Default([lcfit])

#env.Latexdiff(target='diff.tex',source=['stored_alpha.tex','lcfit.tex'])
#diff = env.PDF(target='diff.pdf',source='diff.tex')

# Depends(Flatten([lcfit),
#         Flatten([pdfs, 'lcfit.bib', 'alpha_supp.tex', 'defs.tex']))

cont_build = env.Command('.continuous', ['lcfit.tex'],
#cont_build = env.Command('.continuous', ['lcfit.bib', 'lcfit.tex'],
    'while :; do inotifywait -e modify $SOURCES; scons -Q; done')
Alias('continuous', cont_build)
