---
title: "lcfit distribution performance"
author: "Brian Claywell"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(fig.width = 14, fig.height = 9, dpi = 72, fig.path='figures/',
                      echo = FALSE, warning = FALSE, message = FALSE)

options(scipen = 1, digits = 2)

suppressPackageStartupMessages(library(dplyr))
library(ggplot2)

my_theme <- theme_bw() +
  theme(legend.position = "bottom")

my_theme_vx <- my_theme +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

my_legend <- guides(color = guide_legend(override.aes = list(alpha = 1)))

lcfit.dists.evals <- tbl_df(read.csv('runs/agg_bls.csv', header = TRUE)) %>%
  rename(t = branch_length, rate.dist = rdist_name, model = model_name,
         rate = branch_length_rate) %>%
  mutate(rate = sprintf("Exp(mu=%.2f)", 1/rate),
         method = "normal")

join.keys <- c('node_id', 'n_sites', 'n_leaves', 'rate.dist', 'model',
               'seed', 'rate', 'source_tree', 'method')
```


# Non-iterative lcfit

```{r compute_dists}
logsumexp <- function(x) {
  x_max <- max(x)
  log(sum(exp(x - x_max))) + x_max
}

kl_log <- function(log_freqs1, log_freqs2) {
  log_freqs1 <- log_freqs1 - logsumexp(log_freqs1)
  log_freqs2 <- log_freqs2 - logsumexp(log_freqs2)
  LR <- log_freqs1 - log_freqs2
  sum(exp(log_freqs1) * LR) / log(2)
}

hellinger_log <- function(log_freqs1, log_freqs2) {
  log_freqs1 <- log_freqs1 - logsumexp(log_freqs1)
  log_freqs2 <- log_freqs2 - logsumexp(log_freqs2)
  sqrt(sum((sqrt(exp(log_freqs1)) - sqrt(exp(log_freqs2)))^2)) / sqrt(2)
}

by.node <- group_by(lcfit.dists.evals, node_id, n_sites, n_leaves, rate.dist, 
                    model, seed, rate, source_tree, method)

lcfit.dists <- summarise(by.node, 
                         kl = kl_log(bpp_ll, fit_ll), 
                         hellinger = hellinger_log(bpp_ll, fit_ll))
```

```{r compare_dists.kl}
p.kl <- ggplot(lcfit.dists, aes(x = model, y = kl, fill = factor(rate.dist))) +
  facet_grid(seed ~ rate) +
  xlab("model") +
  ylab("KL divergence (bits)") +
  my_theme_vx +
  my_legend

p.kl +
  geom_boxplot() +
  ggtitle("Kullback-Leibler divergence between empirical and lcfit likelihoods at sampled branch lengths")

# based on http://stackoverflow.com/a/5678146
# compute the upper whisker for each condition
kl.lims <- group_by(lcfit.dists, model, rate, rate.dist, seed) %>%
  summarise(ymax = boxplot.stats(kl)$stats[5])

kl.ylim1 <- c(0, max(kl.lims$ymax))

p.kl +
  geom_boxplot() +
  coord_cartesian(ylim = 1.05 * kl.ylim1) +
  ggtitle(paste("Kullback-Leibler divergence between empirical and lcfit likelihoods at sampled branch lengths\n",
                "(some outliers suppressed)"))
```

```{r compare_dists.hellinger}
p.hellinger <- ggplot(lcfit.dists, aes(x = model, y = hellinger, fill = factor(rate.dist))) +
  facet_grid(seed ~ rate) +
  xlab("model") +
  ylab("Hellinger distance") +
  my_theme_vx +
  my_legend

p.hellinger +
  geom_boxplot() +
  ggtitle("Hellinger distance between empirical and lcfit likelihoods at sampled branch lengths")
```

```{r join_data}

source('tidy_data.R')

lcfit.joined <- left_join(lcfit, lcfit.dists, by = join.keys)
```

```{r kl.vs.t_ml}

p.kl.vs.t_ml <- ggplot(filter(lcfit.joined, kl < 100, t_ml < 2),
                       aes(x = t_ml, y = kl, color = factor(rate.dist))) +
  facet_grid(model ~ rate, scales = "free_x") +
  xlab(expression(t)) +
  ylab("KL divergence (bits)") +
  my_theme +
  my_legend

p.kl.vs.t_ml +
  geom_point(alpha = 0.5) +
  ggtitle("KL divergence vs maximum likelihood branch length")
```

```{r hellinger.vs.t_ml}
p.kl.vs.t_ml %+% filter(lcfit.joined, t_ml < 2) +
  ylab("Hellinger distance") +
  geom_point(aes(y = hellinger), alpha = 0.5) +
  ggtitle("Hellinger distance vs maximum likelihood branch length")
```
