---
title: "lcfit performance evaluations"
author: "Brian Claywell"
date: "`r format(Sys.time(), %F %X')`"
output: html_document
---


```{r setup, echo=FALSE}
knitr::opts_chunk$set(fig.width = 14, fig.height = 9, dpi = 72, fig.path='figures/',
                      echo = FALSE, warning = FALSE, message = FALSE)

options(scipen = 1, digits = 2)

suppressPackageStartupMessages(library(dplyr))
library(ggplot2)

my_theme <- theme_bw() +
  theme(legend.position = "bottom")

my_theme_vx <- my_theme +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

my_legend <- guides(color = guide_legend(override.aes = list(alpha = 1)))

source('tidy_data.R')

models <- unique(lcfit$model)
rate.dists <- unique(lcfit$rate.dist)
rates <- unique(lcfit$rate)
tolerances <- unique(lcfit$tolerance)

nestly.keys <- c('node_id', 't_ml', 'n_sites', 'n_leaves', 'rate.dist', 'model',
                 'seed', 'rate', 'tolerance', 'source_tree')
```

# Non-iterative lcfit


---------------------   ---------------------------------------------
Models                  `r models`

Rate distributions      `r rate.dists`

Rates                   `r rates`

Number of replicates    `r length(unique(lcfit$seed))`

Number of evaluations   `r nrow(filter(lcfit, method == "normal"))`

Number of failures      `r nrow(filter(lcfit, method == "normal", is.na(t_hat)))`
---------------------   ---------------------------------------------


## Failures


```{r}
as.data.frame(filter(lcfit, method == "normal", is.na(t_hat)))
lcfit.noniter <- filter(lcfit, method == "normal", !is.na(t_hat))
```

Remaining evaluations: `r nrow(lcfit.noniter)`


## Plots


```{r noniter.t_vs_that.facets}

p.t_vs_that <- ggplot(lcfit.noniter,
                      aes(x = t_ml, y = t_hat, color = factor(rate))) +
  geom_abline(slope = 1) +
  facet_grid(rate.dist ~ model) +
  scale_y_log10() +
  scale_x_log10() +
  ylab(expression(hat(t))) +
  xlab(expression(t)) +
  my_theme_vx +
  my_legend

p.t_vs_that +
  geom_point(alpha = 0.2) +
  ggtitle("Comparison of fit branch lengths (non-iterative)")

```

```{r noniter.rel_err.facets}
p.rel_err <- ggplot(lcfit.noniter,
                    aes(x = t_ml, y = rel.err, color = factor(rate))) +
  facet_grid(rate.dist ~ model) +
  scale_y_log10() +
  ylab(expression(abs(frac(t - hat(t), t)))) +
  xlab(expression(t)) +
  my_theme_vx +
  my_legend

p.rel_err +
  geom_point(alpha = 0.2) +
  ggtitle("Relative error (non-iterative)")

```


# Iterative lcfit


---------------------   ---------------------------------------------
Models                  `r models`

Rate distributions      `r rate.dists`

Rates                   `r rates`

Tolerances              `r tolerances`

Number of replicates    `r length(unique(lcfit$seed))`

Number of evaluations   `r nrow(filter(lcfit, method == "iterative"))`

Number of failures      `r nrow(filter(lcfit, method == "iterative", is.na(t_hat)))`
---------------------   ---------------------------------------------


## Failures


```{r}

as.data.frame(filter(lcfit, method == "iterative", is.na(t_hat)))
lcfit.iter <- filter(lcfit, method == "iterative", !is.na(t_hat))
lcfit.brent <- filter(lcfit, method == "brent", !is.na(t_hat))
```


Let's remove the failures from the non-iterative evaluations from consideration, too.


```{r, echo=TRUE}
lcfit.iter <- anti_join(lcfit.iter, filter(lcfit, method == "normal", is.na(t_hat)),
                        by = nestly.keys[nestly.keys != "tolerance"])
lcfit.brent <- anti_join(lcfit.brent, filter(lcfit, method == "normal", is.na(t_hat)),
                         by = nestly.keys[nestly.keys != "tolerance"])
```

Remaining evaluations: `r nrow(lcfit.iter)`


## Plots


```{r iter.t_vs_that}

p.t_vs_that %+% lcfit.iter +
  geom_point(alpha = 0.2) +
  ggtitle("Comparison of fit branch lengths (iterative)")
```

```{r iter.rel_err}
p.rel_err %+% lcfit.iter +
  geom_point(alpha = 0.2) +
  ggtitle("Relative error (iterative)")
```

```{r}
lcfit.iter_vs_brent <- left_join(lcfit.iter, lcfit.brent, by = nestly.keys) %>%
  filter(method.x == "iterative", method.y == "brent") %>%
  mutate(eval.ratio = n_eval.x / n_eval.y)
```

```{r iter.vs_brent}
p.iter.vs_brent <- ggplot(lcfit.iter_vs_brent,
                          aes(x = n_eval.x, y = n_eval.y,
                              color = factor(tolerance, levels = c(1e-2, 1e-3, 1e-4, 1e-5, 1e-6)))) +
  geom_abline() +
  expand_limits(x = 0, y = 0) +
  ylab("log-likelihood evaluations (Brent)") +
  xlab("log-likelihood evaluations (lcfit)") +
  my_theme +
  my_legend

p.iter.vs_brent +
  geom_jitter(alpha = 0.2) +
  ggtitle("Log-likelihood evaluations, Brent vs lcfit")
```

```{r iter.vs_brent.facets}
p.iter.vs_brent +
  geom_jitter(alpha = 0.2) +
  facet_grid(rate.dist ~ model) +
  ggtitle("Log-likelihood evaluations, Brent vs lcfit")
```


# Iterative vs non-iterative lcfit

```{r combined.err}

lcfit.filtered <- union(lcfit.noniter, union(lcfit.iter, lcfit.brent))

p.err <-
  ggplot(lcfit.filtered,
         aes(fill = factor(tolerance, levels = c(1e-2, 1e-3, 1e-4, 1e-5, 1e-6)),
             y = err, x = factor(method, levels = c('normal', 'iterative', 'brent')))) +
  geom_hline(yintercept = 0, linetype = 'dashed') +
  scale_fill_discrete("tolerance") +
  ylab(expression(t - hat(t))) +
  xlab("method") +
  my_theme

p.err +
  geom_boxplot() +
  ggtitle("Maximum likelihood branch length estimation error")

# based on http://stackoverflow.com/a/5678146
# compute lower and upper whiskers (stats[c(1, 5)]) or box hinges (stats[c(2, 4]))
ylim1 <- boxplot.stats(filter(lcfit.filtered, method == 'iterative', tolerance == 0.01)$err)$stats[c(1, 5)]
ylim2 <- boxplot.stats(filter(lcfit.filtered, method == 'iterative', tolerance == 0.001)$err)$stats[c(1, 5)]

# scale y limits based on ylim1
p.err +
  geom_boxplot(outlier.shape = NA) +
  coord_cartesian(ylim = ylim1*1.05) +
  ggtitle("Maximum likelihood branch length estimation error (zoom 1, outliers suppressed)")

# scale y limits based on ylim2
p.err +
  geom_boxplot(outlier.shape = NA) +
  coord_cartesian(ylim = ylim2*1.05) +
  ggtitle("Maximum likelihood branch length estimation error (zoom 2, outliers suppressed)")
```
