// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_bsm_scale_factor
double rcpp_bsm_scale_factor(const double t, const double l, const List model);
RcppExport SEXP lcfit_rcpp_bsm_scale_factor(SEXP tSEXP, SEXP lSEXP, SEXP modelSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const double >::type t(tSEXP );
        Rcpp::traits::input_parameter< const double >::type l(lSEXP );
        Rcpp::traits::input_parameter< const List >::type model(modelSEXP );
        double __result = rcpp_bsm_scale_factor(t, l, model);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// rcpp_bsm_rescale
NumericVector rcpp_bsm_rescale(const double t, const double l, List model);
RcppExport SEXP lcfit_rcpp_bsm_rescale(SEXP tSEXP, SEXP lSEXP, SEXP modelSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const double >::type t(tSEXP );
        Rcpp::traits::input_parameter< const double >::type l(lSEXP );
        Rcpp::traits::input_parameter< List >::type model(modelSEXP );
        NumericVector __result = rcpp_bsm_rescale(t, l, model);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// rcpp_fit_bsm
NumericVector rcpp_fit_bsm(NumericVector t, NumericVector l, List model);
RcppExport SEXP lcfit_rcpp_fit_bsm(SEXP tSEXP, SEXP lSEXP, SEXP modelSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type l(lSEXP );
        Rcpp::traits::input_parameter< List >::type model(modelSEXP );
        NumericVector __result = rcpp_fit_bsm(t, l, model);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
