# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lcfit_bsm_scale_factor <- function(t, l, model) {
    .Call('lcfit_rcpp_bsm_scale_factor', PACKAGE = 'lcfit', t, l, model)
}

lcfit_bsm_rescale <- function(bl, ll, model) {
    .Call('lcfit_rcpp_bsm_rescale', PACKAGE = 'lcfit', bl, ll, model)
}

lcfit_fit_bsm <- function(bl, ll, w, model, max_iter) {
    .Call('lcfit_rcpp_fit_bsm', PACKAGE = 'lcfit', bl, ll, w, model, max_iter)
}

